sudo: required
language: c
compiler: gcc
os: linux

before_script:
    - sudo apt-get update
    - sudo apt-get -y install libfftw3-dev ffmpeg gnuplot

script:
    - cd tests
    - make
    - ./tests

notifications:
    email: false
