sudo: required
language: c
compiler: gcc
os: linux

before_script:
    - sudo apt-get update
    - sudo apt-get -y install libfftw3-dev ffmpeg gnuplot

script:
    - mkdir build
    - cd build
    - mkdir images
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - make
    - make test

notifications:
    email: false
