sudo: required
language: c
compiler: gcc
os: linux
addons:
  apt:
    sources:
    - sourceline: 'ppa:duggan/bats'
    packages:
    - libfftw3-dev
    - ffmpeg
    - gnuplot

script:
    # Compilation in the build/ directory
    - mkdir build
    - cd build
    - mkdir images
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - make -s -j4
    # Run the tests
    - make test

notifications:
    email: false
