sudo: required
language: c
compiler: gcc
os: linux
addons:
  apt:
    sources:
        - sourceline: 'ppa:duggan/bats'
    packages:
        - libpulse-dev
        - pulseaudio
        - libfftw3-dev
        - ffmpeg
        - gnuplot

script:
    # Installing the python extension
    - pip3 install -U pip
    - pip3 install .
    # Compilation in the build/ directory
    - mkdir build
    - cd build
    - mkdir images
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=YES
    - make -s -j4
    # Run the tests
    - make test

notifications:
    email: false
