name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
      name: Create Release
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Uploading Release Assets
          uses: softprops/action-gh-release@v1
          with:
            body: ""
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pypi:
      name: Upload to PyPi
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@master

        - name: Setup python
          uses: actions/setup-python@v1
          with:
            python-version: 3.6
            architecture: x64

        - name: Building
          run: |
            python3 -m pip install wheel
            python3 setup.py sdist bdist_wheel

        - name: Uploading
          env:
            TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
            TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          run: |
            python3 -m pip install twine
            python3 -m twine upload dist/*
